### ISSUE TITLE
Investigate SERVER_DOWN issue on bullseye

### ISSUE THREAD

**Issue by Mstrodl** [liam-middlebrook/csh_ldap#33]
Something wonky happened between libldap `2.4.47` and `2.4.59` that causes bullseye's libldap `2.4.57` to give us `SERVER_DOWN` errors when attempting to connect:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ldap/ldapobject.py", line 1196, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/local/lib/python3.9/site-packages/ldap/ldapobject.py", line 443, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/local/lib/python3.9/site-packages/ldap/ldapobject.py", line 437, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/local/lib/python3.9/site-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/local/lib/python3.9/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/local/lib/python3.9/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 9, 'info': '(unknown error code)'}
```

This isn't great because we tend not to pin our container images to a particular release. We have a lot of things that have `python:3.9.7` instead of `python:3.9.7-buster`. When these projects get rebuilt by OKD, stuff breaks because it can't talk to LDAP.

**Comment by WillNilges** [comment]
Can we revert this guy back to a working version of LDAP in the meantime, or should we move all our projects back to buster?

**Comment by Mstrodl** [comment]
> Can we revert this guy back to a working version of LDAP in the meantime, or should we move all our projects back to buster?
> 
> Oh wait, is this a problem with the Debian package?

Bullseye ships libldap with a regression, and it's unlikely to be fixed because that's kinda their whole meme (:sparkles: stability :sparkles:)

It's fixed in newer libldap and older libldap (as in buster) doesn't have the issue

You may have luck with alpine or debian bookworm (unsure if python projects tend to build that or not... I'm not a doctor)

**Comment by alfonsrv** [comment]
What works is setting the the `ldap.OPT_X_TLS_REQUIRE_CERT` option via monkey-patching globally.

```python
import ldap
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
```

**Comment by Mstrodl** [comment]
I think we did eventually land on that, I probably should've updated this issue. Thanks!
Nowadays we just use bookworm so it's not such a big deal.

**Comment by alfonsrv** [comment]
Same issue still persists in bookworm – I'm using `python:3.11-slim`

**Comment by Mstrodl** [comment]
Oh weird

**Comment by mxmeinhold** [comment]
on bullseye, libldap-dev does not install libldap-common as a dependency. Installing libldap-common seems to resolve the issues
